/*
 * Copyright 2022 CloudWeGo Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by hertz generator.

package main

import (
	"context"
	"os"

	"github.com/PBH-BTN/trunker/biz/config"
	"github.com/PBH-BTN/trunker/biz/services/interval"
	"github.com/PBH-BTN/trunker/biz/services/peer"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
)

func main() {
	config.Init()
	//database.Init()
	//cache.Init()
	peer.LoadPeer()
	h := server.Default()
	if os.Getenv("RUN_ENV") == "prod" {
		hlog.SetLevel(hlog.LevelInfo)
	}
	register(h)
	h.Engine.OnShutdown = append(h.Engine.OnShutdown, func(_ context.Context) {
		// here save current data
		peer.SavePeer()
	})
	interval.StartIntervalTask()
	h.Spin()
}
