// Code generated by Kitex v0.12.3. DO NOT EDIT.

package trunkerservice

import (
	"context"
	trunker "github.com/PBH-BTN/trunker/kitex_gen/pbh/btn/trunker"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Announce(ctx context.Context, request *trunker.AnnounceRequest, callOptions ...callopt.Option) (r *trunker.AnnounceResponse, err error)
	Scrape(ctx context.Context, request *trunker.ScrapeRequest, callOptions ...callopt.Option) (r *trunker.ScrapeResponse, err error)
	GetStatistic(ctx context.Context, request *trunker.GetStatisticRequest, callOptions ...callopt.Option) (r *trunker.GetStatisticResponse, err error)
	Ban(ctx context.Context, request *trunker.BanRequest, callOptions ...callopt.Option) (r *trunker.BanResponse, err error)
	DeleteInfoHash(ctx context.Context, request *trunker.DeleteInfoHashRequest, callOptions ...callopt.Option) (r *trunker.DeleteInfoHashResponse, err error)
	GetPeer(ctx context.Context, request *trunker.GetPeerRequest, callOptions ...callopt.Option) (r *trunker.GetPeerResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kTrunkerServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kTrunkerServiceClient struct {
	*kClient
}

func (p *kTrunkerServiceClient) Announce(ctx context.Context, request *trunker.AnnounceRequest, callOptions ...callopt.Option) (r *trunker.AnnounceResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Announce(ctx, request)
}

func (p *kTrunkerServiceClient) Scrape(ctx context.Context, request *trunker.ScrapeRequest, callOptions ...callopt.Option) (r *trunker.ScrapeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Scrape(ctx, request)
}

func (p *kTrunkerServiceClient) GetStatistic(ctx context.Context, request *trunker.GetStatisticRequest, callOptions ...callopt.Option) (r *trunker.GetStatisticResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetStatistic(ctx, request)
}

func (p *kTrunkerServiceClient) Ban(ctx context.Context, request *trunker.BanRequest, callOptions ...callopt.Option) (r *trunker.BanResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Ban(ctx, request)
}

func (p *kTrunkerServiceClient) DeleteInfoHash(ctx context.Context, request *trunker.DeleteInfoHashRequest, callOptions ...callopt.Option) (r *trunker.DeleteInfoHashResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteInfoHash(ctx, request)
}

func (p *kTrunkerServiceClient) GetPeer(ctx context.Context, request *trunker.GetPeerRequest, callOptions ...callopt.Option) (r *trunker.GetPeerResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPeer(ctx, request)
}
