// Code generated by Kitex v0.12.3. DO NOT EDIT.

package trunkerservice

import (
	"context"
	"errors"
	trunker "github.com/PBH-BTN/trunker/kitex_gen/pbh/btn/trunker"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Announce": kitex.NewMethodInfo(
		announceHandler,
		newTrunkerServiceAnnounceArgs,
		newTrunkerServiceAnnounceResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	trunkerServiceServiceInfo                = NewServiceInfo()
	trunkerServiceServiceInfoForClient       = NewServiceInfoForClient()
	trunkerServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return trunkerServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return trunkerServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return trunkerServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "TrunkerService"
	handlerType := (*trunker.TrunkerService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "trunker",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.12.3",
		Extra:           extra,
	}
	return svcInfo
}

func announceHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*trunker.TrunkerServiceAnnounceArgs)
	realResult := result.(*trunker.TrunkerServiceAnnounceResult)
	success, err := handler.(trunker.TrunkerService).Announce(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTrunkerServiceAnnounceArgs() interface{} {
	return trunker.NewTrunkerServiceAnnounceArgs()
}

func newTrunkerServiceAnnounceResult() interface{} {
	return trunker.NewTrunkerServiceAnnounceResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Announce(ctx context.Context, request *trunker.AnnounceRequest) (r *trunker.AnnounceResponse, err error) {
	var _args trunker.TrunkerServiceAnnounceArgs
	_args.Request = request
	var _result trunker.TrunkerServiceAnnounceResult
	if err = p.c.Call(ctx, "Announce", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
