database:
  database: test
  host: localhost
  port: 3306
  user: test
  pass: password123

cache:
  host: localhost
  port: 6379

tracker:
  ttl: 3600
  intervalTask: 600 # 10分钟执行一次定时任务
  useDB: false
  enablePersist: true
  maxPeersPerTorrent: 1500
  shard: 40
  useUnixSocket: false
  hostPorts: 127.0.0.1:8888
  useAnnounceIP: true
  enableEventProducer: false

rocketmq:
  topic: TrunkerEvent
  endpoint: localhost:8081