cache:
  enable: false
  network: tcp # tcp or unix
  addr: localhost:6379

tracker:
  ttl: 3600
  intervalTask: 600 # 10分钟执行一次定时任务
  mode: memory # memory or db
  memory:
    enablePersist: true
    persistFile: persist.dat
    maxPeersPerTorrent: 1500
    shard: 40
  rpc:
    enableServer: false
    hostPorts: 0.0.0.0:6789
    remoteServer: localhost:6789
  database:
    database: test
    host: localhost
    port: 3306
    user: trunker
    pass: password123
  useUnixSocket: false
  hostPorts: 127.0.0.1:8888
  useAnnounceIP: true
  enableEventProducer: false
  enableMetrics: false
  metricsHostPorts: 0.0.0.0:9091
  udpServer:
    enable: true
    hostPorts: :6881
  wsServer:
    enable: true
    shard: 10
  trackerId: default # https://wiki.theory.org/BitTorrentSpecification#Tracker_HTTP.2FHTTPS_Protocol
rocketmq:
  topic: TrunkerEvent
  endpoint: localhost:8081