database:
  database: root
  host: localhost
  port: 3306
  user: root
  pass: root

cache:
  host: localhost
  port: 6379

tracker:
  ttl: 3600
  intervalTask: 600 # 10分钟执行一次定时任务
  useDB: false
  enablePersist: false
  maxPeersPerTorrent: 1500
  shard: 40
  useUnixSocket: true
  hostPorts: ingress.sock
  useAnnounceIP: true
  enableEventProducer: true

rocketmq:
  topic: TrunkerEvent
  endpoint: 127.0.0.1:8081