// Code generated by thriftgo (0.3.18). DO NOT EDIT.

package trunker

import (
	"bytes"
	"database/sql"
	"database/sql/driver"
	"fmt"
	"strings"
)

type PeerEvent int64

const (
	PeerEvent_unknown   PeerEvent = 0
	PeerEvent_started   PeerEvent = 1
	PeerEvent_stopped   PeerEvent = 2
	PeerEvent_completed PeerEvent = 3
)

func (p PeerEvent) String() string {
	switch p {
	case PeerEvent_unknown:
		return "unknown"
	case PeerEvent_started:
		return "started"
	case PeerEvent_stopped:
		return "stopped"
	case PeerEvent_completed:
		return "completed"
	}
	return "<UNSET>"
}

func PeerEventFromString(s string) (PeerEvent, error) {
	switch s {
	case "unknown":
		return PeerEvent_unknown, nil
	case "started":
		return PeerEvent_started, nil
	case "stopped":
		return PeerEvent_stopped, nil
	case "completed":
		return PeerEvent_completed, nil
	}
	return PeerEvent(0), fmt.Errorf("not a valid PeerEvent string")
}

func PeerEventPtr(v PeerEvent) *PeerEvent { return &v }
func (p *PeerEvent) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = PeerEvent(result.Int64)
	return
}

func (p *PeerEvent) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type PeerType int64

const (
	PeerType_Bittorrent PeerType = 0
	PeerType_Webtorrent PeerType = 1
)

func (p PeerType) String() string {
	switch p {
	case PeerType_Bittorrent:
		return "Bittorrent"
	case PeerType_Webtorrent:
		return "Webtorrent"
	}
	return "<UNSET>"
}

func PeerTypeFromString(s string) (PeerType, error) {
	switch s {
	case "Bittorrent":
		return PeerType_Bittorrent, nil
	case "Webtorrent":
		return PeerType_Webtorrent, nil
	}
	return PeerType(0), fmt.Errorf("not a valid PeerType string")
}

func PeerTypePtr(v PeerType) *PeerType { return &v }
func (p *PeerType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = PeerType(result.Int64)
	return
}

func (p *PeerType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type Source int64

const (
	Source_HTTP Source = 0
	Source_UDP  Source = 1
	Source_WS   Source = 2
)

func (p Source) String() string {
	switch p {
	case Source_HTTP:
		return "HTTP"
	case Source_UDP:
		return "UDP"
	case Source_WS:
		return "WS"
	}
	return "<UNSET>"
}

func SourceFromString(s string) (Source, error) {
	switch s {
	case "HTTP":
		return Source_HTTP, nil
	case "UDP":
		return Source_UDP, nil
	case "WS":
		return Source_WS, nil
	}
	return Source(0), fmt.Errorf("not a valid Source string")
}

func SourcePtr(v Source) *Source { return &v }
func (p *Source) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = Source(result.Int64)
	return
}

func (p *Source) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type Offer struct {
	OfferId string       `thrift:"offer_id,1,required" frugal:"1,required,string" json:"offer_id"`
	Offer   *OfferDetail `thrift:"offer,2,required" frugal:"2,required,OfferDetail" json:"offer"`
}

func NewOffer() *Offer {
	return &Offer{}
}

func (p *Offer) InitDefault() {
}

func (p *Offer) GetOfferId() (v string) {
	return p.OfferId
}

var Offer_Offer_DEFAULT *OfferDetail

func (p *Offer) GetOffer() (v *OfferDetail) {
	if !p.IsSetOffer() {
		return Offer_Offer_DEFAULT
	}
	return p.Offer
}
func (p *Offer) SetOfferId(val string) {
	p.OfferId = val
}
func (p *Offer) SetOffer(val *OfferDetail) {
	p.Offer = val
}

func (p *Offer) IsSetOffer() bool {
	return p.Offer != nil
}

func (p *Offer) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Offer(%+v)", *p)
}

func (p *Offer) DeepEqual(ano *Offer) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.OfferId) {
		return false
	}
	if !p.Field2DeepEqual(ano.Offer) {
		return false
	}
	return true
}

func (p *Offer) Field1DeepEqual(src string) bool {

	if strings.Compare(p.OfferId, src) != 0 {
		return false
	}
	return true
}
func (p *Offer) Field2DeepEqual(src *OfferDetail) bool {

	if !p.Offer.DeepEqual(src) {
		return false
	}
	return true
}

type OfferDetail struct {
	Type string `thrift:"type,1,required" frugal:"1,required,string" json:"type"`
	Sdp  string `thrift:"sdp,2,required" frugal:"2,required,string" json:"sdp"`
}

func NewOfferDetail() *OfferDetail {
	return &OfferDetail{}
}

func (p *OfferDetail) InitDefault() {
}

func (p *OfferDetail) GetType() (v string) {
	return p.Type
}

func (p *OfferDetail) GetSdp() (v string) {
	return p.Sdp
}
func (p *OfferDetail) SetType(val string) {
	p.Type = val
}
func (p *OfferDetail) SetSdp(val string) {
	p.Sdp = val
}

func (p *OfferDetail) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OfferDetail(%+v)", *p)
}

func (p *OfferDetail) DeepEqual(ano *OfferDetail) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Type) {
		return false
	}
	if !p.Field2DeepEqual(ano.Sdp) {
		return false
	}
	return true
}

func (p *OfferDetail) Field1DeepEqual(src string) bool {

	if strings.Compare(p.Type, src) != 0 {
		return false
	}
	return true
}
func (p *OfferDetail) Field2DeepEqual(src string) bool {

	if strings.Compare(p.Sdp, src) != 0 {
		return false
	}
	return true
}

type Peer struct {
	Ip         []byte    `thrift:"ip,1,required" frugal:"1,required,binary" json:"ip"`
	Ipv4       []byte    `thrift:"ipv4,2" frugal:"2,default,binary" json:"ipv4"`
	Ipv6       []byte    `thrift:"ipv6,3" frugal:"3,default,binary" json:"ipv6"`
	ClientIp   []byte    `thrift:"client_ip,4" frugal:"4,default,binary" json:"client_ip"`
	LastSeen   int64     `thrift:"last_seen,5,required" frugal:"5,required,i64" json:"last_seen"`
	Offers     []*Offer  `thrift:"offers,6,optional" frugal:"6,optional,list<Offer>" json:"offers,omitempty"`
	Id         string    `thrift:"id,7,required" frugal:"7,required,string" json:"id"`
	UserAgent  string    `thrift:"user_agent,8,required" frugal:"8,required,string" json:"user_agent"`
	Port       int32     `thrift:"port,9,required" frugal:"9,required,i32" json:"port"`
	Uploaded   int64     `thrift:"uploaded,10,required" frugal:"10,required,i64" json:"uploaded"`
	Downloaded int64     `thrift:"downloaded,11,required" frugal:"11,required,i64" json:"downloaded"`
	Left       int64     `thrift:"left,12,required" frugal:"12,required,i64" json:"left"`
	Type       PeerType  `thrift:"type,13,required" frugal:"13,required,PeerType" json:"type"`
	Event      PeerEvent `thrift:"event,14,required" frugal:"14,required,PeerEvent" json:"event"`
	Source     Source    `thrift:"source,15,required" frugal:"15,required,Source" json:"source"`
}

func NewPeer() *Peer {
	return &Peer{}
}

func (p *Peer) InitDefault() {
}

func (p *Peer) GetIp() (v []byte) {
	return p.Ip
}

func (p *Peer) GetIpv4() (v []byte) {
	return p.Ipv4
}

func (p *Peer) GetIpv6() (v []byte) {
	return p.Ipv6
}

func (p *Peer) GetClientIp() (v []byte) {
	return p.ClientIp
}

func (p *Peer) GetLastSeen() (v int64) {
	return p.LastSeen
}

var Peer_Offers_DEFAULT []*Offer

func (p *Peer) GetOffers() (v []*Offer) {
	if !p.IsSetOffers() {
		return Peer_Offers_DEFAULT
	}
	return p.Offers
}

func (p *Peer) GetId() (v string) {
	return p.Id
}

func (p *Peer) GetUserAgent() (v string) {
	return p.UserAgent
}

func (p *Peer) GetPort() (v int32) {
	return p.Port
}

func (p *Peer) GetUploaded() (v int64) {
	return p.Uploaded
}

func (p *Peer) GetDownloaded() (v int64) {
	return p.Downloaded
}

func (p *Peer) GetLeft() (v int64) {
	return p.Left
}

func (p *Peer) GetType() (v PeerType) {
	return p.Type
}

func (p *Peer) GetEvent() (v PeerEvent) {
	return p.Event
}

func (p *Peer) GetSource() (v Source) {
	return p.Source
}
func (p *Peer) SetIp(val []byte) {
	p.Ip = val
}
func (p *Peer) SetIpv4(val []byte) {
	p.Ipv4 = val
}
func (p *Peer) SetIpv6(val []byte) {
	p.Ipv6 = val
}
func (p *Peer) SetClientIp(val []byte) {
	p.ClientIp = val
}
func (p *Peer) SetLastSeen(val int64) {
	p.LastSeen = val
}
func (p *Peer) SetOffers(val []*Offer) {
	p.Offers = val
}
func (p *Peer) SetId(val string) {
	p.Id = val
}
func (p *Peer) SetUserAgent(val string) {
	p.UserAgent = val
}
func (p *Peer) SetPort(val int32) {
	p.Port = val
}
func (p *Peer) SetUploaded(val int64) {
	p.Uploaded = val
}
func (p *Peer) SetDownloaded(val int64) {
	p.Downloaded = val
}
func (p *Peer) SetLeft(val int64) {
	p.Left = val
}
func (p *Peer) SetType(val PeerType) {
	p.Type = val
}
func (p *Peer) SetEvent(val PeerEvent) {
	p.Event = val
}
func (p *Peer) SetSource(val Source) {
	p.Source = val
}

func (p *Peer) IsSetOffers() bool {
	return p.Offers != nil
}

func (p *Peer) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Peer(%+v)", *p)
}

func (p *Peer) DeepEqual(ano *Peer) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Ip) {
		return false
	}
	if !p.Field2DeepEqual(ano.Ipv4) {
		return false
	}
	if !p.Field3DeepEqual(ano.Ipv6) {
		return false
	}
	if !p.Field4DeepEqual(ano.ClientIp) {
		return false
	}
	if !p.Field5DeepEqual(ano.LastSeen) {
		return false
	}
	if !p.Field6DeepEqual(ano.Offers) {
		return false
	}
	if !p.Field7DeepEqual(ano.Id) {
		return false
	}
	if !p.Field8DeepEqual(ano.UserAgent) {
		return false
	}
	if !p.Field9DeepEqual(ano.Port) {
		return false
	}
	if !p.Field10DeepEqual(ano.Uploaded) {
		return false
	}
	if !p.Field11DeepEqual(ano.Downloaded) {
		return false
	}
	if !p.Field12DeepEqual(ano.Left) {
		return false
	}
	if !p.Field13DeepEqual(ano.Type) {
		return false
	}
	if !p.Field14DeepEqual(ano.Event) {
		return false
	}
	if !p.Field15DeepEqual(ano.Source) {
		return false
	}
	return true
}

func (p *Peer) Field1DeepEqual(src []byte) bool {

	if bytes.Compare(p.Ip, src) != 0 {
		return false
	}
	return true
}
func (p *Peer) Field2DeepEqual(src []byte) bool {

	if bytes.Compare(p.Ipv4, src) != 0 {
		return false
	}
	return true
}
func (p *Peer) Field3DeepEqual(src []byte) bool {

	if bytes.Compare(p.Ipv6, src) != 0 {
		return false
	}
	return true
}
func (p *Peer) Field4DeepEqual(src []byte) bool {

	if bytes.Compare(p.ClientIp, src) != 0 {
		return false
	}
	return true
}
func (p *Peer) Field5DeepEqual(src int64) bool {

	if p.LastSeen != src {
		return false
	}
	return true
}
func (p *Peer) Field6DeepEqual(src []*Offer) bool {

	if len(p.Offers) != len(src) {
		return false
	}
	for i, v := range p.Offers {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}
func (p *Peer) Field7DeepEqual(src string) bool {

	if strings.Compare(p.Id, src) != 0 {
		return false
	}
	return true
}
func (p *Peer) Field8DeepEqual(src string) bool {

	if strings.Compare(p.UserAgent, src) != 0 {
		return false
	}
	return true
}
func (p *Peer) Field9DeepEqual(src int32) bool {

	if p.Port != src {
		return false
	}
	return true
}
func (p *Peer) Field10DeepEqual(src int64) bool {

	if p.Uploaded != src {
		return false
	}
	return true
}
func (p *Peer) Field11DeepEqual(src int64) bool {

	if p.Downloaded != src {
		return false
	}
	return true
}
func (p *Peer) Field12DeepEqual(src int64) bool {

	if p.Left != src {
		return false
	}
	return true
}
func (p *Peer) Field13DeepEqual(src PeerType) bool {

	if p.Type != src {
		return false
	}
	return true
}
func (p *Peer) Field14DeepEqual(src PeerEvent) bool {

	if p.Event != src {
		return false
	}
	return true
}
func (p *Peer) Field15DeepEqual(src Source) bool {

	if p.Source != src {
		return false
	}
	return true
}

type ScrapeFile struct {
	Complete   int64 `thrift:"complete,1,required" frugal:"1,required,i64" json:"complete"`
	Downloaded int64 `thrift:"downloaded,2,required" frugal:"2,required,i64" json:"downloaded"`
	Incomplete int64 `thrift:"incomplete,3,required" frugal:"3,required,i64" json:"incomplete"`
	Seeder     int64 `thrift:"seeder,4,required" frugal:"4,required,i64" json:"seeder"`
}

func NewScrapeFile() *ScrapeFile {
	return &ScrapeFile{}
}

func (p *ScrapeFile) InitDefault() {
}

func (p *ScrapeFile) GetComplete() (v int64) {
	return p.Complete
}

func (p *ScrapeFile) GetDownloaded() (v int64) {
	return p.Downloaded
}

func (p *ScrapeFile) GetIncomplete() (v int64) {
	return p.Incomplete
}

func (p *ScrapeFile) GetSeeder() (v int64) {
	return p.Seeder
}
func (p *ScrapeFile) SetComplete(val int64) {
	p.Complete = val
}
func (p *ScrapeFile) SetDownloaded(val int64) {
	p.Downloaded = val
}
func (p *ScrapeFile) SetIncomplete(val int64) {
	p.Incomplete = val
}
func (p *ScrapeFile) SetSeeder(val int64) {
	p.Seeder = val
}

func (p *ScrapeFile) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ScrapeFile(%+v)", *p)
}

func (p *ScrapeFile) DeepEqual(ano *ScrapeFile) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Complete) {
		return false
	}
	if !p.Field2DeepEqual(ano.Downloaded) {
		return false
	}
	if !p.Field3DeepEqual(ano.Incomplete) {
		return false
	}
	if !p.Field4DeepEqual(ano.Seeder) {
		return false
	}
	return true
}

func (p *ScrapeFile) Field1DeepEqual(src int64) bool {

	if p.Complete != src {
		return false
	}
	return true
}
func (p *ScrapeFile) Field2DeepEqual(src int64) bool {

	if p.Downloaded != src {
		return false
	}
	return true
}
func (p *ScrapeFile) Field3DeepEqual(src int64) bool {

	if p.Incomplete != src {
		return false
	}
	return true
}
func (p *ScrapeFile) Field4DeepEqual(src int64) bool {

	if p.Seeder != src {
		return false
	}
	return true
}

type StatisticInfo struct {
	TotalPeers    int64                     `thrift:"total_peers,1,required" frugal:"1,required,i64" json:"total_peers"`
	TotalTorrents int64                     `thrift:"total_torrents,2,required" frugal:"2,required,i64" json:"total_torrents"`
	Shards        map[string]*StatisticInfo `thrift:"shards,3,optional" frugal:"3,optional,map<string:StatisticInfo>" json:"shards,omitempty"`
}

func NewStatisticInfo() *StatisticInfo {
	return &StatisticInfo{}
}

func (p *StatisticInfo) InitDefault() {
}

func (p *StatisticInfo) GetTotalPeers() (v int64) {
	return p.TotalPeers
}

func (p *StatisticInfo) GetTotalTorrents() (v int64) {
	return p.TotalTorrents
}

var StatisticInfo_Shards_DEFAULT map[string]*StatisticInfo

func (p *StatisticInfo) GetShards() (v map[string]*StatisticInfo) {
	if !p.IsSetShards() {
		return StatisticInfo_Shards_DEFAULT
	}
	return p.Shards
}
func (p *StatisticInfo) SetTotalPeers(val int64) {
	p.TotalPeers = val
}
func (p *StatisticInfo) SetTotalTorrents(val int64) {
	p.TotalTorrents = val
}
func (p *StatisticInfo) SetShards(val map[string]*StatisticInfo) {
	p.Shards = val
}

func (p *StatisticInfo) IsSetShards() bool {
	return p.Shards != nil
}

func (p *StatisticInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StatisticInfo(%+v)", *p)
}

func (p *StatisticInfo) DeepEqual(ano *StatisticInfo) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.TotalPeers) {
		return false
	}
	if !p.Field2DeepEqual(ano.TotalTorrents) {
		return false
	}
	if !p.Field3DeepEqual(ano.Shards) {
		return false
	}
	return true
}

func (p *StatisticInfo) Field1DeepEqual(src int64) bool {

	if p.TotalPeers != src {
		return false
	}
	return true
}
func (p *StatisticInfo) Field2DeepEqual(src int64) bool {

	if p.TotalTorrents != src {
		return false
	}
	return true
}
func (p *StatisticInfo) Field3DeepEqual(src map[string]*StatisticInfo) bool {

	if len(p.Shards) != len(src) {
		return false
	}
	for k, v := range p.Shards {
		_src := src[k]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}
