// Code generated by Kitex v0.12.3. DO NOT EDIT.

package trunker

import (
	"bytes"
	"fmt"
	"reflect"
	"strings"

	"github.com/cloudwego/gopkg/protocol/thrift"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = thrift.STOP
)

type TrunkerServiceAnnounceArgs struct {
	Request *AnnounceRequest `thrift:"request,1" frugal:"1,default,AnnounceRequest" json:"request"`
}

func NewTrunkerServiceAnnounceArgs() *TrunkerServiceAnnounceArgs {
	return &TrunkerServiceAnnounceArgs{}
}

func (p *TrunkerServiceAnnounceArgs) InitDefault() {
}

var TrunkerServiceAnnounceArgs_Request_DEFAULT *AnnounceRequest

func (p *TrunkerServiceAnnounceArgs) GetRequest() (v *AnnounceRequest) {
	if !p.IsSetRequest() {
		return TrunkerServiceAnnounceArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *TrunkerServiceAnnounceArgs) SetRequest(val *AnnounceRequest) {
	p.Request = val
}

func (p *TrunkerServiceAnnounceArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *TrunkerServiceAnnounceArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TrunkerServiceAnnounceArgs(%+v)", *p)
}

func (p *TrunkerServiceAnnounceArgs) GetFirstArgument() interface{} {
	return p.Request
}

type TrunkerServiceAnnounceResult struct {
	Success *AnnounceResponse `thrift:"success,0,optional" frugal:"0,optional,AnnounceResponse" json:"success,omitempty"`
}

func NewTrunkerServiceAnnounceResult() *TrunkerServiceAnnounceResult {
	return &TrunkerServiceAnnounceResult{}
}

func (p *TrunkerServiceAnnounceResult) InitDefault() {
}

var TrunkerServiceAnnounceResult_Success_DEFAULT *AnnounceResponse

func (p *TrunkerServiceAnnounceResult) GetSuccess() (v *AnnounceResponse) {
	if !p.IsSetSuccess() {
		return TrunkerServiceAnnounceResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TrunkerServiceAnnounceResult) SetSuccess(x interface{}) {
	p.Success = x.(*AnnounceResponse)
}

func (p *TrunkerServiceAnnounceResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TrunkerServiceAnnounceResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TrunkerServiceAnnounceResult(%+v)", *p)
}

func (p *TrunkerServiceAnnounceResult) GetResult() interface{} {
	return p.Success
}

type TrunkerServiceScrapeArgs struct {
	Request *ScrapeRequest `thrift:"request,1" frugal:"1,default,ScrapeRequest" json:"request"`
}

func NewTrunkerServiceScrapeArgs() *TrunkerServiceScrapeArgs {
	return &TrunkerServiceScrapeArgs{}
}

func (p *TrunkerServiceScrapeArgs) InitDefault() {
}

var TrunkerServiceScrapeArgs_Request_DEFAULT *ScrapeRequest

func (p *TrunkerServiceScrapeArgs) GetRequest() (v *ScrapeRequest) {
	if !p.IsSetRequest() {
		return TrunkerServiceScrapeArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *TrunkerServiceScrapeArgs) SetRequest(val *ScrapeRequest) {
	p.Request = val
}

func (p *TrunkerServiceScrapeArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *TrunkerServiceScrapeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TrunkerServiceScrapeArgs(%+v)", *p)
}

func (p *TrunkerServiceScrapeArgs) GetFirstArgument() interface{} {
	return p.Request
}

type TrunkerServiceScrapeResult struct {
	Success *ScrapeResponse `thrift:"success,0,optional" frugal:"0,optional,ScrapeResponse" json:"success,omitempty"`
}

func NewTrunkerServiceScrapeResult() *TrunkerServiceScrapeResult {
	return &TrunkerServiceScrapeResult{}
}

func (p *TrunkerServiceScrapeResult) InitDefault() {
}

var TrunkerServiceScrapeResult_Success_DEFAULT *ScrapeResponse

func (p *TrunkerServiceScrapeResult) GetSuccess() (v *ScrapeResponse) {
	if !p.IsSetSuccess() {
		return TrunkerServiceScrapeResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TrunkerServiceScrapeResult) SetSuccess(x interface{}) {
	p.Success = x.(*ScrapeResponse)
}

func (p *TrunkerServiceScrapeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TrunkerServiceScrapeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TrunkerServiceScrapeResult(%+v)", *p)
}

func (p *TrunkerServiceScrapeResult) GetResult() interface{} {
	return p.Success
}

type TrunkerServiceGetStatisticArgs struct {
	Request *GetStatisticRequest `thrift:"request,1" frugal:"1,default,GetStatisticRequest" json:"request"`
}

func NewTrunkerServiceGetStatisticArgs() *TrunkerServiceGetStatisticArgs {
	return &TrunkerServiceGetStatisticArgs{}
}

func (p *TrunkerServiceGetStatisticArgs) InitDefault() {
}

var TrunkerServiceGetStatisticArgs_Request_DEFAULT *GetStatisticRequest

func (p *TrunkerServiceGetStatisticArgs) GetRequest() (v *GetStatisticRequest) {
	if !p.IsSetRequest() {
		return TrunkerServiceGetStatisticArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *TrunkerServiceGetStatisticArgs) SetRequest(val *GetStatisticRequest) {
	p.Request = val
}

func (p *TrunkerServiceGetStatisticArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *TrunkerServiceGetStatisticArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TrunkerServiceGetStatisticArgs(%+v)", *p)
}

func (p *TrunkerServiceGetStatisticArgs) GetFirstArgument() interface{} {
	return p.Request
}

type TrunkerServiceGetStatisticResult struct {
	Success *GetStatisticResponse `thrift:"success,0,optional" frugal:"0,optional,GetStatisticResponse" json:"success,omitempty"`
}

func NewTrunkerServiceGetStatisticResult() *TrunkerServiceGetStatisticResult {
	return &TrunkerServiceGetStatisticResult{}
}

func (p *TrunkerServiceGetStatisticResult) InitDefault() {
}

var TrunkerServiceGetStatisticResult_Success_DEFAULT *GetStatisticResponse

func (p *TrunkerServiceGetStatisticResult) GetSuccess() (v *GetStatisticResponse) {
	if !p.IsSetSuccess() {
		return TrunkerServiceGetStatisticResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TrunkerServiceGetStatisticResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetStatisticResponse)
}

func (p *TrunkerServiceGetStatisticResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TrunkerServiceGetStatisticResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TrunkerServiceGetStatisticResult(%+v)", *p)
}

func (p *TrunkerServiceGetStatisticResult) GetResult() interface{} {
	return p.Success
}

type TrunkerServiceBanArgs struct {
	Request *BanRequest `thrift:"request,1" frugal:"1,default,BanRequest" json:"request"`
}

func NewTrunkerServiceBanArgs() *TrunkerServiceBanArgs {
	return &TrunkerServiceBanArgs{}
}

func (p *TrunkerServiceBanArgs) InitDefault() {
}

var TrunkerServiceBanArgs_Request_DEFAULT *BanRequest

func (p *TrunkerServiceBanArgs) GetRequest() (v *BanRequest) {
	if !p.IsSetRequest() {
		return TrunkerServiceBanArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *TrunkerServiceBanArgs) SetRequest(val *BanRequest) {
	p.Request = val
}

func (p *TrunkerServiceBanArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *TrunkerServiceBanArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TrunkerServiceBanArgs(%+v)", *p)
}

func (p *TrunkerServiceBanArgs) GetFirstArgument() interface{} {
	return p.Request
}

type TrunkerServiceBanResult struct {
	Success *BanResponse `thrift:"success,0,optional" frugal:"0,optional,BanResponse" json:"success,omitempty"`
}

func NewTrunkerServiceBanResult() *TrunkerServiceBanResult {
	return &TrunkerServiceBanResult{}
}

func (p *TrunkerServiceBanResult) InitDefault() {
}

var TrunkerServiceBanResult_Success_DEFAULT *BanResponse

func (p *TrunkerServiceBanResult) GetSuccess() (v *BanResponse) {
	if !p.IsSetSuccess() {
		return TrunkerServiceBanResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TrunkerServiceBanResult) SetSuccess(x interface{}) {
	p.Success = x.(*BanResponse)
}

func (p *TrunkerServiceBanResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TrunkerServiceBanResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TrunkerServiceBanResult(%+v)", *p)
}

func (p *TrunkerServiceBanResult) GetResult() interface{} {
	return p.Success
}

type TrunkerServiceDeleteInfoHashArgs struct {
	Request *DeleteInfoHashRequest `thrift:"request,1" frugal:"1,default,DeleteInfoHashRequest" json:"request"`
}

func NewTrunkerServiceDeleteInfoHashArgs() *TrunkerServiceDeleteInfoHashArgs {
	return &TrunkerServiceDeleteInfoHashArgs{}
}

func (p *TrunkerServiceDeleteInfoHashArgs) InitDefault() {
}

var TrunkerServiceDeleteInfoHashArgs_Request_DEFAULT *DeleteInfoHashRequest

func (p *TrunkerServiceDeleteInfoHashArgs) GetRequest() (v *DeleteInfoHashRequest) {
	if !p.IsSetRequest() {
		return TrunkerServiceDeleteInfoHashArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *TrunkerServiceDeleteInfoHashArgs) SetRequest(val *DeleteInfoHashRequest) {
	p.Request = val
}

func (p *TrunkerServiceDeleteInfoHashArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *TrunkerServiceDeleteInfoHashArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TrunkerServiceDeleteInfoHashArgs(%+v)", *p)
}

func (p *TrunkerServiceDeleteInfoHashArgs) GetFirstArgument() interface{} {
	return p.Request
}

type TrunkerServiceDeleteInfoHashResult struct {
	Success *DeleteInfoHashResponse `thrift:"success,0,optional" frugal:"0,optional,DeleteInfoHashResponse" json:"success,omitempty"`
}

func NewTrunkerServiceDeleteInfoHashResult() *TrunkerServiceDeleteInfoHashResult {
	return &TrunkerServiceDeleteInfoHashResult{}
}

func (p *TrunkerServiceDeleteInfoHashResult) InitDefault() {
}

var TrunkerServiceDeleteInfoHashResult_Success_DEFAULT *DeleteInfoHashResponse

func (p *TrunkerServiceDeleteInfoHashResult) GetSuccess() (v *DeleteInfoHashResponse) {
	if !p.IsSetSuccess() {
		return TrunkerServiceDeleteInfoHashResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TrunkerServiceDeleteInfoHashResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeleteInfoHashResponse)
}

func (p *TrunkerServiceDeleteInfoHashResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TrunkerServiceDeleteInfoHashResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TrunkerServiceDeleteInfoHashResult(%+v)", *p)
}

func (p *TrunkerServiceDeleteInfoHashResult) GetResult() interface{} {
	return p.Success
}

type TrunkerServiceGetPeerArgs struct {
	Request *GetPeerRequest `thrift:"request,1" frugal:"1,default,GetPeerRequest" json:"request"`
}

func NewTrunkerServiceGetPeerArgs() *TrunkerServiceGetPeerArgs {
	return &TrunkerServiceGetPeerArgs{}
}

func (p *TrunkerServiceGetPeerArgs) InitDefault() {
}

var TrunkerServiceGetPeerArgs_Request_DEFAULT *GetPeerRequest

func (p *TrunkerServiceGetPeerArgs) GetRequest() (v *GetPeerRequest) {
	if !p.IsSetRequest() {
		return TrunkerServiceGetPeerArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *TrunkerServiceGetPeerArgs) SetRequest(val *GetPeerRequest) {
	p.Request = val
}

func (p *TrunkerServiceGetPeerArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *TrunkerServiceGetPeerArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TrunkerServiceGetPeerArgs(%+v)", *p)
}

func (p *TrunkerServiceGetPeerArgs) GetFirstArgument() interface{} {
	return p.Request
}

type TrunkerServiceGetPeerResult struct {
	Success *GetPeerResponse `thrift:"success,0,optional" frugal:"0,optional,GetPeerResponse" json:"success,omitempty"`
}

func NewTrunkerServiceGetPeerResult() *TrunkerServiceGetPeerResult {
	return &TrunkerServiceGetPeerResult{}
}

func (p *TrunkerServiceGetPeerResult) InitDefault() {
}

var TrunkerServiceGetPeerResult_Success_DEFAULT *GetPeerResponse

func (p *TrunkerServiceGetPeerResult) GetSuccess() (v *GetPeerResponse) {
	if !p.IsSetSuccess() {
		return TrunkerServiceGetPeerResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TrunkerServiceGetPeerResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetPeerResponse)
}

func (p *TrunkerServiceGetPeerResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TrunkerServiceGetPeerResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TrunkerServiceGetPeerResult(%+v)", *p)
}

func (p *TrunkerServiceGetPeerResult) GetResult() interface{} {
	return p.Success
}
