// Code generated by Kitex v0.12.3. DO NOT EDIT.

package trunker

import (
	"bytes"
	"fmt"
	"reflect"
	"strings"

	"github.com/cloudwego/gopkg/protocol/thrift"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = thrift.STOP
)

type TrunkerServiceAnnounceArgs struct {
	Request *AnnounceRequest `thrift:"request,1" frugal:"1,default,AnnounceRequest" json:"request"`
}

func NewTrunkerServiceAnnounceArgs() *TrunkerServiceAnnounceArgs {
	return &TrunkerServiceAnnounceArgs{}
}

func (p *TrunkerServiceAnnounceArgs) InitDefault() {
}

var TrunkerServiceAnnounceArgs_Request_DEFAULT *AnnounceRequest

func (p *TrunkerServiceAnnounceArgs) GetRequest() (v *AnnounceRequest) {
	if !p.IsSetRequest() {
		return TrunkerServiceAnnounceArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *TrunkerServiceAnnounceArgs) SetRequest(val *AnnounceRequest) {
	p.Request = val
}

func (p *TrunkerServiceAnnounceArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *TrunkerServiceAnnounceArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TrunkerServiceAnnounceArgs(%+v)", *p)
}

func (p *TrunkerServiceAnnounceArgs) GetFirstArgument() interface{} {
	return p.Request
}

type TrunkerServiceAnnounceResult struct {
	Success *AnnounceResponse `thrift:"success,0,optional" frugal:"0,optional,AnnounceResponse" json:"success,omitempty"`
}

func NewTrunkerServiceAnnounceResult() *TrunkerServiceAnnounceResult {
	return &TrunkerServiceAnnounceResult{}
}

func (p *TrunkerServiceAnnounceResult) InitDefault() {
}

var TrunkerServiceAnnounceResult_Success_DEFAULT *AnnounceResponse

func (p *TrunkerServiceAnnounceResult) GetSuccess() (v *AnnounceResponse) {
	if !p.IsSetSuccess() {
		return TrunkerServiceAnnounceResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TrunkerServiceAnnounceResult) SetSuccess(x interface{}) {
	p.Success = x.(*AnnounceResponse)
}

func (p *TrunkerServiceAnnounceResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TrunkerServiceAnnounceResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TrunkerServiceAnnounceResult(%+v)", *p)
}

func (p *TrunkerServiceAnnounceResult) GetResult() interface{} {
	return p.Success
}
