// Code generated by thriftgo (0.3.18). DO NOT EDIT.

package trunker

import (
	"bytes"
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
	"strings"
)

type BanType int64

const (
	BanType_InfoHash BanType = 0
	BanType_PeerID   BanType = 1
)

func (p BanType) String() string {
	switch p {
	case BanType_InfoHash:
		return "InfoHash"
	case BanType_PeerID:
		return "PeerID"
	}
	return "<UNSET>"
}

func BanTypeFromString(s string) (BanType, error) {
	switch s {
	case "InfoHash":
		return BanType_InfoHash, nil
	case "PeerID":
		return BanType_PeerID, nil
	}
	return BanType(0), fmt.Errorf("not a valid BanType string")
}

func BanTypePtr(v BanType) *BanType { return &v }
func (p *BanType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = BanType(result.Int64)
	return
}

func (p *BanType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type AnnounceRequest struct {
	Offers     []*Offer  `thrift:"offers,1,optional" frugal:"1,optional,list<Offer>" json:"offers,omitempty"`
	ClientIp   []byte    `thrift:"client_ip,2,required" frugal:"2,required,binary" json:"client_ip"`
	InfoHash   string    `thrift:"info_hash,3,required" frugal:"3,required,string" json:"info_hash"`
	PeerId     string    `thrift:"peer_id,4,required" frugal:"4,required,string" json:"peer_id"`
	Ip         string    `thrift:"ip,5,required" frugal:"5,required,string" json:"ip"`
	Ipv4       string    `thrift:"ipv4,6" frugal:"6,default,string" json:"ipv4"`
	Ipv6       string    `thrift:"ipv6,7" frugal:"7,default,string" json:"ipv6"`
	Downloaded int64     `thrift:"downloaded,8,required" frugal:"8,required,i64" json:"downloaded"`
	Left       int64     `thrift:"left,9,required" frugal:"9,required,i64" json:"left"`
	Uploaded   int64     `thrift:"uploaded,10,required" frugal:"10,required,i64" json:"uploaded"`
	NumWant    int64     `thrift:"num_want,11,required" frugal:"11,required,i64" json:"num_want"`
	Type       PeerType  `thrift:"type,12,required" frugal:"12,required,PeerType" json:"type"`
	Source     Source    `thrift:"source,13,required" frugal:"13,required,Source" json:"source"`
	Event      PeerEvent `thrift:"event,14,required" frugal:"14,required,PeerEvent" json:"event"`
	Port       int32     `thrift:"port,15,required" frugal:"15,required,i32" json:"port"`
	Compact    bool      `thrift:"compact,16" frugal:"16,default,bool" json:"compact"`
}

func NewAnnounceRequest() *AnnounceRequest {
	return &AnnounceRequest{}
}

func (p *AnnounceRequest) InitDefault() {
}

var AnnounceRequest_Offers_DEFAULT []*Offer

func (p *AnnounceRequest) GetOffers() (v []*Offer) {
	if !p.IsSetOffers() {
		return AnnounceRequest_Offers_DEFAULT
	}
	return p.Offers
}

func (p *AnnounceRequest) GetClientIp() (v []byte) {
	return p.ClientIp
}

func (p *AnnounceRequest) GetInfoHash() (v string) {
	return p.InfoHash
}

func (p *AnnounceRequest) GetPeerId() (v string) {
	return p.PeerId
}

func (p *AnnounceRequest) GetIp() (v string) {
	return p.Ip
}

func (p *AnnounceRequest) GetIpv4() (v string) {
	return p.Ipv4
}

func (p *AnnounceRequest) GetIpv6() (v string) {
	return p.Ipv6
}

func (p *AnnounceRequest) GetDownloaded() (v int64) {
	return p.Downloaded
}

func (p *AnnounceRequest) GetLeft() (v int64) {
	return p.Left
}

func (p *AnnounceRequest) GetUploaded() (v int64) {
	return p.Uploaded
}

func (p *AnnounceRequest) GetNumWant() (v int64) {
	return p.NumWant
}

func (p *AnnounceRequest) GetType() (v PeerType) {
	return p.Type
}

func (p *AnnounceRequest) GetSource() (v Source) {
	return p.Source
}

func (p *AnnounceRequest) GetEvent() (v PeerEvent) {
	return p.Event
}

func (p *AnnounceRequest) GetPort() (v int32) {
	return p.Port
}

func (p *AnnounceRequest) GetCompact() (v bool) {
	return p.Compact
}
func (p *AnnounceRequest) SetOffers(val []*Offer) {
	p.Offers = val
}
func (p *AnnounceRequest) SetClientIp(val []byte) {
	p.ClientIp = val
}
func (p *AnnounceRequest) SetInfoHash(val string) {
	p.InfoHash = val
}
func (p *AnnounceRequest) SetPeerId(val string) {
	p.PeerId = val
}
func (p *AnnounceRequest) SetIp(val string) {
	p.Ip = val
}
func (p *AnnounceRequest) SetIpv4(val string) {
	p.Ipv4 = val
}
func (p *AnnounceRequest) SetIpv6(val string) {
	p.Ipv6 = val
}
func (p *AnnounceRequest) SetDownloaded(val int64) {
	p.Downloaded = val
}
func (p *AnnounceRequest) SetLeft(val int64) {
	p.Left = val
}
func (p *AnnounceRequest) SetUploaded(val int64) {
	p.Uploaded = val
}
func (p *AnnounceRequest) SetNumWant(val int64) {
	p.NumWant = val
}
func (p *AnnounceRequest) SetType(val PeerType) {
	p.Type = val
}
func (p *AnnounceRequest) SetSource(val Source) {
	p.Source = val
}
func (p *AnnounceRequest) SetEvent(val PeerEvent) {
	p.Event = val
}
func (p *AnnounceRequest) SetPort(val int32) {
	p.Port = val
}
func (p *AnnounceRequest) SetCompact(val bool) {
	p.Compact = val
}

func (p *AnnounceRequest) IsSetOffers() bool {
	return p.Offers != nil
}

func (p *AnnounceRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AnnounceRequest(%+v)", *p)
}

func (p *AnnounceRequest) DeepEqual(ano *AnnounceRequest) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Offers) {
		return false
	}
	if !p.Field2DeepEqual(ano.ClientIp) {
		return false
	}
	if !p.Field3DeepEqual(ano.InfoHash) {
		return false
	}
	if !p.Field4DeepEqual(ano.PeerId) {
		return false
	}
	if !p.Field5DeepEqual(ano.Ip) {
		return false
	}
	if !p.Field6DeepEqual(ano.Ipv4) {
		return false
	}
	if !p.Field7DeepEqual(ano.Ipv6) {
		return false
	}
	if !p.Field8DeepEqual(ano.Downloaded) {
		return false
	}
	if !p.Field9DeepEqual(ano.Left) {
		return false
	}
	if !p.Field10DeepEqual(ano.Uploaded) {
		return false
	}
	if !p.Field11DeepEqual(ano.NumWant) {
		return false
	}
	if !p.Field12DeepEqual(ano.Type) {
		return false
	}
	if !p.Field13DeepEqual(ano.Source) {
		return false
	}
	if !p.Field14DeepEqual(ano.Event) {
		return false
	}
	if !p.Field15DeepEqual(ano.Port) {
		return false
	}
	if !p.Field16DeepEqual(ano.Compact) {
		return false
	}
	return true
}

func (p *AnnounceRequest) Field1DeepEqual(src []*Offer) bool {

	if len(p.Offers) != len(src) {
		return false
	}
	for i, v := range p.Offers {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}
func (p *AnnounceRequest) Field2DeepEqual(src []byte) bool {

	if bytes.Compare(p.ClientIp, src) != 0 {
		return false
	}
	return true
}
func (p *AnnounceRequest) Field3DeepEqual(src string) bool {

	if strings.Compare(p.InfoHash, src) != 0 {
		return false
	}
	return true
}
func (p *AnnounceRequest) Field4DeepEqual(src string) bool {

	if strings.Compare(p.PeerId, src) != 0 {
		return false
	}
	return true
}
func (p *AnnounceRequest) Field5DeepEqual(src string) bool {

	if strings.Compare(p.Ip, src) != 0 {
		return false
	}
	return true
}
func (p *AnnounceRequest) Field6DeepEqual(src string) bool {

	if strings.Compare(p.Ipv4, src) != 0 {
		return false
	}
	return true
}
func (p *AnnounceRequest) Field7DeepEqual(src string) bool {

	if strings.Compare(p.Ipv6, src) != 0 {
		return false
	}
	return true
}
func (p *AnnounceRequest) Field8DeepEqual(src int64) bool {

	if p.Downloaded != src {
		return false
	}
	return true
}
func (p *AnnounceRequest) Field9DeepEqual(src int64) bool {

	if p.Left != src {
		return false
	}
	return true
}
func (p *AnnounceRequest) Field10DeepEqual(src int64) bool {

	if p.Uploaded != src {
		return false
	}
	return true
}
func (p *AnnounceRequest) Field11DeepEqual(src int64) bool {

	if p.NumWant != src {
		return false
	}
	return true
}
func (p *AnnounceRequest) Field12DeepEqual(src PeerType) bool {

	if p.Type != src {
		return false
	}
	return true
}
func (p *AnnounceRequest) Field13DeepEqual(src Source) bool {

	if p.Source != src {
		return false
	}
	return true
}
func (p *AnnounceRequest) Field14DeepEqual(src PeerEvent) bool {

	if p.Event != src {
		return false
	}
	return true
}
func (p *AnnounceRequest) Field15DeepEqual(src int32) bool {

	if p.Port != src {
		return false
	}
	return true
}
func (p *AnnounceRequest) Field16DeepEqual(src bool) bool {

	if p.Compact != src {
		return false
	}
	return true
}

type AnnounceResponse struct {
	Peers []*Peer `thrift:"peers,1,required" frugal:"1,required,list<Peer>" json:"peers"`
}

func NewAnnounceResponse() *AnnounceResponse {
	return &AnnounceResponse{}
}

func (p *AnnounceResponse) InitDefault() {
}

func (p *AnnounceResponse) GetPeers() (v []*Peer) {
	return p.Peers
}
func (p *AnnounceResponse) SetPeers(val []*Peer) {
	p.Peers = val
}

func (p *AnnounceResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AnnounceResponse(%+v)", *p)
}

func (p *AnnounceResponse) DeepEqual(ano *AnnounceResponse) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Peers) {
		return false
	}
	return true
}

func (p *AnnounceResponse) Field1DeepEqual(src []*Peer) bool {

	if len(p.Peers) != len(src) {
		return false
	}
	for i, v := range p.Peers {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}

type ScrapeRequest struct {
	InfoHashes []string `thrift:"info_hashes,1,required" frugal:"1,required,list<string>" json:"info_hashes"`
}

func NewScrapeRequest() *ScrapeRequest {
	return &ScrapeRequest{}
}

func (p *ScrapeRequest) InitDefault() {
}

func (p *ScrapeRequest) GetInfoHashes() (v []string) {
	return p.InfoHashes
}
func (p *ScrapeRequest) SetInfoHashes(val []string) {
	p.InfoHashes = val
}

func (p *ScrapeRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ScrapeRequest(%+v)", *p)
}

func (p *ScrapeRequest) DeepEqual(ano *ScrapeRequest) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.InfoHashes) {
		return false
	}
	return true
}

func (p *ScrapeRequest) Field1DeepEqual(src []string) bool {

	if len(p.InfoHashes) != len(src) {
		return false
	}
	for i, v := range p.InfoHashes {
		_src := src[i]
		if strings.Compare(v, _src) != 0 {
			return false
		}
	}
	return true
}

type ScrapeResponse struct {
	Res map[string]*ScrapeFile `thrift:"res,1,required" frugal:"1,required,map<string:ScrapeFile>" json:"res"`
}

func NewScrapeResponse() *ScrapeResponse {
	return &ScrapeResponse{}
}

func (p *ScrapeResponse) InitDefault() {
}

func (p *ScrapeResponse) GetRes() (v map[string]*ScrapeFile) {
	return p.Res
}
func (p *ScrapeResponse) SetRes(val map[string]*ScrapeFile) {
	p.Res = val
}

func (p *ScrapeResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ScrapeResponse(%+v)", *p)
}

func (p *ScrapeResponse) DeepEqual(ano *ScrapeResponse) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Res) {
		return false
	}
	return true
}

func (p *ScrapeResponse) Field1DeepEqual(src map[string]*ScrapeFile) bool {

	if len(p.Res) != len(src) {
		return false
	}
	for k, v := range p.Res {
		_src := src[k]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}

type GetStatisticRequest struct {
}

func NewGetStatisticRequest() *GetStatisticRequest {
	return &GetStatisticRequest{}
}

func (p *GetStatisticRequest) InitDefault() {
}

func (p *GetStatisticRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetStatisticRequest(%+v)", *p)
}

func (p *GetStatisticRequest) DeepEqual(ano *GetStatisticRequest) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	return true
}

type GetStatisticResponse struct {
	Info *StatisticInfo `thrift:"info,1,required" frugal:"1,required,StatisticInfo" json:"info"`
}

func NewGetStatisticResponse() *GetStatisticResponse {
	return &GetStatisticResponse{}
}

func (p *GetStatisticResponse) InitDefault() {
}

var GetStatisticResponse_Info_DEFAULT *StatisticInfo

func (p *GetStatisticResponse) GetInfo() (v *StatisticInfo) {
	if !p.IsSetInfo() {
		return GetStatisticResponse_Info_DEFAULT
	}
	return p.Info
}
func (p *GetStatisticResponse) SetInfo(val *StatisticInfo) {
	p.Info = val
}

func (p *GetStatisticResponse) IsSetInfo() bool {
	return p.Info != nil
}

func (p *GetStatisticResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetStatisticResponse(%+v)", *p)
}

func (p *GetStatisticResponse) DeepEqual(ano *GetStatisticResponse) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Info) {
		return false
	}
	return true
}

func (p *GetStatisticResponse) Field1DeepEqual(src *StatisticInfo) bool {

	if !p.Info.DeepEqual(src) {
		return false
	}
	return true
}

type BanRequest struct {
	Type   BanType `thrift:"type,1,required" frugal:"1,required,BanType" json:"type"`
	Target string  `thrift:"target,2,required" frugal:"2,required,string" json:"target"`
}

func NewBanRequest() *BanRequest {
	return &BanRequest{}
}

func (p *BanRequest) InitDefault() {
}

func (p *BanRequest) GetType() (v BanType) {
	return p.Type
}

func (p *BanRequest) GetTarget() (v string) {
	return p.Target
}
func (p *BanRequest) SetType(val BanType) {
	p.Type = val
}
func (p *BanRequest) SetTarget(val string) {
	p.Target = val
}

func (p *BanRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BanRequest(%+v)", *p)
}

func (p *BanRequest) DeepEqual(ano *BanRequest) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Type) {
		return false
	}
	if !p.Field2DeepEqual(ano.Target) {
		return false
	}
	return true
}

func (p *BanRequest) Field1DeepEqual(src BanType) bool {

	if p.Type != src {
		return false
	}
	return true
}
func (p *BanRequest) Field2DeepEqual(src string) bool {

	if strings.Compare(p.Target, src) != 0 {
		return false
	}
	return true
}

type BanResponse struct {
}

func NewBanResponse() *BanResponse {
	return &BanResponse{}
}

func (p *BanResponse) InitDefault() {
}

func (p *BanResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BanResponse(%+v)", *p)
}

func (p *BanResponse) DeepEqual(ano *BanResponse) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	return true
}

type DeleteInfoHashRequest struct {
	Target string `thrift:"target,1,required" frugal:"1,required,string" json:"target"`
}

func NewDeleteInfoHashRequest() *DeleteInfoHashRequest {
	return &DeleteInfoHashRequest{}
}

func (p *DeleteInfoHashRequest) InitDefault() {
}

func (p *DeleteInfoHashRequest) GetTarget() (v string) {
	return p.Target
}
func (p *DeleteInfoHashRequest) SetTarget(val string) {
	p.Target = val
}

func (p *DeleteInfoHashRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteInfoHashRequest(%+v)", *p)
}

func (p *DeleteInfoHashRequest) DeepEqual(ano *DeleteInfoHashRequest) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Target) {
		return false
	}
	return true
}

func (p *DeleteInfoHashRequest) Field1DeepEqual(src string) bool {

	if strings.Compare(p.Target, src) != 0 {
		return false
	}
	return true
}

type DeleteInfoHashResponse struct {
}

func NewDeleteInfoHashResponse() *DeleteInfoHashResponse {
	return &DeleteInfoHashResponse{}
}

func (p *DeleteInfoHashResponse) InitDefault() {
}

func (p *DeleteInfoHashResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteInfoHashResponse(%+v)", *p)
}

func (p *DeleteInfoHashResponse) DeepEqual(ano *DeleteInfoHashResponse) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	return true
}

type GetPeerRequest struct {
	InfoHash string `thrift:"info_hash,1,required" frugal:"1,required,string" json:"info_hash"`
}

func NewGetPeerRequest() *GetPeerRequest {
	return &GetPeerRequest{}
}

func (p *GetPeerRequest) InitDefault() {
}

func (p *GetPeerRequest) GetInfoHash() (v string) {
	return p.InfoHash
}
func (p *GetPeerRequest) SetInfoHash(val string) {
	p.InfoHash = val
}

func (p *GetPeerRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetPeerRequest(%+v)", *p)
}

func (p *GetPeerRequest) DeepEqual(ano *GetPeerRequest) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.InfoHash) {
		return false
	}
	return true
}

func (p *GetPeerRequest) Field1DeepEqual(src string) bool {

	if strings.Compare(p.InfoHash, src) != 0 {
		return false
	}
	return true
}

type GetPeerResponse struct {
	Peers []*Peer `thrift:"peers,1,required" frugal:"1,required,list<Peer>" json:"peers"`
}

func NewGetPeerResponse() *GetPeerResponse {
	return &GetPeerResponse{}
}

func (p *GetPeerResponse) InitDefault() {
}

func (p *GetPeerResponse) GetPeers() (v []*Peer) {
	return p.Peers
}
func (p *GetPeerResponse) SetPeers(val []*Peer) {
	p.Peers = val
}

func (p *GetPeerResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetPeerResponse(%+v)", *p)
}

func (p *GetPeerResponse) DeepEqual(ano *GetPeerResponse) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Peers) {
		return false
	}
	return true
}

func (p *GetPeerResponse) Field1DeepEqual(src []*Peer) bool {

	if len(p.Peers) != len(src) {
		return false
	}
	for i, v := range p.Peers {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}

type TrunkerService interface {
	Announce(ctx context.Context, request *AnnounceRequest) (r *AnnounceResponse, err error)

	Scrape(ctx context.Context, request *ScrapeRequest) (r *ScrapeResponse, err error)

	GetStatistic(ctx context.Context, request *GetStatisticRequest) (r *GetStatisticResponse, err error)

	Ban(ctx context.Context, request *BanRequest) (r *BanResponse, err error)

	DeleteInfoHash(ctx context.Context, request *DeleteInfoHashRequest) (r *DeleteInfoHashResponse, err error)

	GetPeer(ctx context.Context, request *GetPeerRequest) (r *GetPeerResponse, err error)
}
