// Code generated by thriftgo (0.3.18). DO NOT EDIT.

package trunker

import (
	"bytes"
	"context"
	"fmt"
	"strings"
)

type AnnounceRequest struct {
	Offers     []*Offer  `thrift:"offers,1,optional" frugal:"1,optional,list<Offer>" json:"offers,omitempty"`
	ClientIp   []byte    `thrift:"client_ip,2,required" frugal:"2,required,binary" json:"client_ip"`
	InfoHash   string    `thrift:"info_hash,3,required" frugal:"3,required,string" json:"info_hash"`
	PeerId     string    `thrift:"peer_id,4,required" frugal:"4,required,string" json:"peer_id"`
	Ip         string    `thrift:"ip,5,required" frugal:"5,required,string" json:"ip"`
	Ipv4       string    `thrift:"ipv4,6" frugal:"6,default,string" json:"ipv4"`
	Ipv6       string    `thrift:"ipv6,7" frugal:"7,default,string" json:"ipv6"`
	Downloaded int64     `thrift:"downloaded,8,required" frugal:"8,required,i64" json:"downloaded"`
	Left       int64     `thrift:"left,9,required" frugal:"9,required,i64" json:"left"`
	Uploaded   int64     `thrift:"uploaded,10,required" frugal:"10,required,i64" json:"uploaded"`
	NumWant    int64     `thrift:"num_want,11,required" frugal:"11,required,i64" json:"num_want"`
	Type       PeerType  `thrift:"type,12,required" frugal:"12,required,PeerType" json:"type"`
	Source     Source    `thrift:"source,13,required" frugal:"13,required,Source" json:"source"`
	Event      PeerEvent `thrift:"event,14,required" frugal:"14,required,PeerEvent" json:"event"`
	Port       int32     `thrift:"port,15,required" frugal:"15,required,i32" json:"port"`
	Compact    bool      `thrift:"compact,16" frugal:"16,default,bool" json:"compact"`
}

func NewAnnounceRequest() *AnnounceRequest {
	return &AnnounceRequest{}
}

func (p *AnnounceRequest) InitDefault() {
}

var AnnounceRequest_Offers_DEFAULT []*Offer

func (p *AnnounceRequest) GetOffers() (v []*Offer) {
	if !p.IsSetOffers() {
		return AnnounceRequest_Offers_DEFAULT
	}
	return p.Offers
}

func (p *AnnounceRequest) GetClientIp() (v []byte) {
	return p.ClientIp
}

func (p *AnnounceRequest) GetInfoHash() (v string) {
	return p.InfoHash
}

func (p *AnnounceRequest) GetPeerId() (v string) {
	return p.PeerId
}

func (p *AnnounceRequest) GetIp() (v string) {
	return p.Ip
}

func (p *AnnounceRequest) GetIpv4() (v string) {
	return p.Ipv4
}

func (p *AnnounceRequest) GetIpv6() (v string) {
	return p.Ipv6
}

func (p *AnnounceRequest) GetDownloaded() (v int64) {
	return p.Downloaded
}

func (p *AnnounceRequest) GetLeft() (v int64) {
	return p.Left
}

func (p *AnnounceRequest) GetUploaded() (v int64) {
	return p.Uploaded
}

func (p *AnnounceRequest) GetNumWant() (v int64) {
	return p.NumWant
}

func (p *AnnounceRequest) GetType() (v PeerType) {
	return p.Type
}

func (p *AnnounceRequest) GetSource() (v Source) {
	return p.Source
}

func (p *AnnounceRequest) GetEvent() (v PeerEvent) {
	return p.Event
}

func (p *AnnounceRequest) GetPort() (v int32) {
	return p.Port
}

func (p *AnnounceRequest) GetCompact() (v bool) {
	return p.Compact
}
func (p *AnnounceRequest) SetOffers(val []*Offer) {
	p.Offers = val
}
func (p *AnnounceRequest) SetClientIp(val []byte) {
	p.ClientIp = val
}
func (p *AnnounceRequest) SetInfoHash(val string) {
	p.InfoHash = val
}
func (p *AnnounceRequest) SetPeerId(val string) {
	p.PeerId = val
}
func (p *AnnounceRequest) SetIp(val string) {
	p.Ip = val
}
func (p *AnnounceRequest) SetIpv4(val string) {
	p.Ipv4 = val
}
func (p *AnnounceRequest) SetIpv6(val string) {
	p.Ipv6 = val
}
func (p *AnnounceRequest) SetDownloaded(val int64) {
	p.Downloaded = val
}
func (p *AnnounceRequest) SetLeft(val int64) {
	p.Left = val
}
func (p *AnnounceRequest) SetUploaded(val int64) {
	p.Uploaded = val
}
func (p *AnnounceRequest) SetNumWant(val int64) {
	p.NumWant = val
}
func (p *AnnounceRequest) SetType(val PeerType) {
	p.Type = val
}
func (p *AnnounceRequest) SetSource(val Source) {
	p.Source = val
}
func (p *AnnounceRequest) SetEvent(val PeerEvent) {
	p.Event = val
}
func (p *AnnounceRequest) SetPort(val int32) {
	p.Port = val
}
func (p *AnnounceRequest) SetCompact(val bool) {
	p.Compact = val
}

func (p *AnnounceRequest) IsSetOffers() bool {
	return p.Offers != nil
}

func (p *AnnounceRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AnnounceRequest(%+v)", *p)
}

func (p *AnnounceRequest) DeepEqual(ano *AnnounceRequest) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Offers) {
		return false
	}
	if !p.Field2DeepEqual(ano.ClientIp) {
		return false
	}
	if !p.Field3DeepEqual(ano.InfoHash) {
		return false
	}
	if !p.Field4DeepEqual(ano.PeerId) {
		return false
	}
	if !p.Field5DeepEqual(ano.Ip) {
		return false
	}
	if !p.Field6DeepEqual(ano.Ipv4) {
		return false
	}
	if !p.Field7DeepEqual(ano.Ipv6) {
		return false
	}
	if !p.Field8DeepEqual(ano.Downloaded) {
		return false
	}
	if !p.Field9DeepEqual(ano.Left) {
		return false
	}
	if !p.Field10DeepEqual(ano.Uploaded) {
		return false
	}
	if !p.Field11DeepEqual(ano.NumWant) {
		return false
	}
	if !p.Field12DeepEqual(ano.Type) {
		return false
	}
	if !p.Field13DeepEqual(ano.Source) {
		return false
	}
	if !p.Field14DeepEqual(ano.Event) {
		return false
	}
	if !p.Field15DeepEqual(ano.Port) {
		return false
	}
	if !p.Field16DeepEqual(ano.Compact) {
		return false
	}
	return true
}

func (p *AnnounceRequest) Field1DeepEqual(src []*Offer) bool {

	if len(p.Offers) != len(src) {
		return false
	}
	for i, v := range p.Offers {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}
func (p *AnnounceRequest) Field2DeepEqual(src []byte) bool {

	if bytes.Compare(p.ClientIp, src) != 0 {
		return false
	}
	return true
}
func (p *AnnounceRequest) Field3DeepEqual(src string) bool {

	if strings.Compare(p.InfoHash, src) != 0 {
		return false
	}
	return true
}
func (p *AnnounceRequest) Field4DeepEqual(src string) bool {

	if strings.Compare(p.PeerId, src) != 0 {
		return false
	}
	return true
}
func (p *AnnounceRequest) Field5DeepEqual(src string) bool {

	if strings.Compare(p.Ip, src) != 0 {
		return false
	}
	return true
}
func (p *AnnounceRequest) Field6DeepEqual(src string) bool {

	if strings.Compare(p.Ipv4, src) != 0 {
		return false
	}
	return true
}
func (p *AnnounceRequest) Field7DeepEqual(src string) bool {

	if strings.Compare(p.Ipv6, src) != 0 {
		return false
	}
	return true
}
func (p *AnnounceRequest) Field8DeepEqual(src int64) bool {

	if p.Downloaded != src {
		return false
	}
	return true
}
func (p *AnnounceRequest) Field9DeepEqual(src int64) bool {

	if p.Left != src {
		return false
	}
	return true
}
func (p *AnnounceRequest) Field10DeepEqual(src int64) bool {

	if p.Uploaded != src {
		return false
	}
	return true
}
func (p *AnnounceRequest) Field11DeepEqual(src int64) bool {

	if p.NumWant != src {
		return false
	}
	return true
}
func (p *AnnounceRequest) Field12DeepEqual(src PeerType) bool {

	if p.Type != src {
		return false
	}
	return true
}
func (p *AnnounceRequest) Field13DeepEqual(src Source) bool {

	if p.Source != src {
		return false
	}
	return true
}
func (p *AnnounceRequest) Field14DeepEqual(src PeerEvent) bool {

	if p.Event != src {
		return false
	}
	return true
}
func (p *AnnounceRequest) Field15DeepEqual(src int32) bool {

	if p.Port != src {
		return false
	}
	return true
}
func (p *AnnounceRequest) Field16DeepEqual(src bool) bool {

	if p.Compact != src {
		return false
	}
	return true
}

type AnnounceResponse struct {
	Peers []*Peer `thrift:"peers,1,required" frugal:"1,required,list<Peer>" json:"peers"`
}

func NewAnnounceResponse() *AnnounceResponse {
	return &AnnounceResponse{}
}

func (p *AnnounceResponse) InitDefault() {
}

func (p *AnnounceResponse) GetPeers() (v []*Peer) {
	return p.Peers
}
func (p *AnnounceResponse) SetPeers(val []*Peer) {
	p.Peers = val
}

func (p *AnnounceResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AnnounceResponse(%+v)", *p)
}

func (p *AnnounceResponse) DeepEqual(ano *AnnounceResponse) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Peers) {
		return false
	}
	return true
}

func (p *AnnounceResponse) Field1DeepEqual(src []*Peer) bool {

	if len(p.Peers) != len(src) {
		return false
	}
	for i, v := range p.Peers {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}

type TrunkerService interface {
	Announce(ctx context.Context, request *AnnounceRequest) (r *AnnounceResponse, err error)
}
