// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v5.29.3
// source: biz/services/peer/mux_local/peer.proto

package mux_local

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PeerEvent int32

const (
	PeerEvent_Unknown   PeerEvent = 0
	PeerEvent_Started   PeerEvent = 1
	PeerEvent_Stopped   PeerEvent = 2
	PeerEvent_Completed PeerEvent = 3
)

// Enum value maps for PeerEvent.
var (
	PeerEvent_name = map[int32]string{
		0: "Unknown",
		1: "Started",
		2: "Stopped",
		3: "Completed",
	}
	PeerEvent_value = map[string]int32{
		"Unknown":   0,
		"Started":   1,
		"Stopped":   2,
		"Completed": 3,
	}
)

func (x PeerEvent) Enum() *PeerEvent {
	p := new(PeerEvent)
	*p = x
	return p
}

func (x PeerEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeerEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_biz_services_peer_mux_local_peer_proto_enumTypes[0].Descriptor()
}

func (PeerEvent) Type() protoreflect.EnumType {
	return &file_biz_services_peer_mux_local_peer_proto_enumTypes[0]
}

func (x PeerEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeerEvent.Descriptor instead.
func (PeerEvent) EnumDescriptor() ([]byte, []int) {
	return file_biz_services_peer_mux_local_peer_proto_rawDescGZIP(), []int{0}
}

type PeerType int32

const (
	PeerType_Bittorrent PeerType = 0
	PeerType_Webtorrent PeerType = 1
)

// Enum value maps for PeerType.
var (
	PeerType_name = map[int32]string{
		0: "Bittorrent",
		1: "Webtorrent",
	}
	PeerType_value = map[string]int32{
		"Bittorrent": 0,
		"Webtorrent": 1,
	}
)

func (x PeerType) Enum() *PeerType {
	p := new(PeerType)
	*p = x
	return p
}

func (x PeerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeerType) Descriptor() protoreflect.EnumDescriptor {
	return file_biz_services_peer_mux_local_peer_proto_enumTypes[1].Descriptor()
}

func (PeerType) Type() protoreflect.EnumType {
	return &file_biz_services_peer_mux_local_peer_proto_enumTypes[1]
}

func (x PeerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeerType.Descriptor instead.
func (PeerType) EnumDescriptor() ([]byte, []int) {
	return file_biz_services_peer_mux_local_peer_proto_rawDescGZIP(), []int{1}
}

type PeerSource int32

const (
	PeerSource_HTTP PeerSource = 0
	PeerSource_UDP  PeerSource = 1
	PeerSource_WS   PeerSource = 2
)

// Enum value maps for PeerSource.
var (
	PeerSource_name = map[int32]string{
		0: "HTTP",
		1: "UDP",
		2: "WS",
	}
	PeerSource_value = map[string]int32{
		"HTTP": 0,
		"UDP":  1,
		"WS":   2,
	}
)

func (x PeerSource) Enum() *PeerSource {
	p := new(PeerSource)
	*p = x
	return p
}

func (x PeerSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeerSource) Descriptor() protoreflect.EnumDescriptor {
	return file_biz_services_peer_mux_local_peer_proto_enumTypes[2].Descriptor()
}

func (PeerSource) Type() protoreflect.EnumType {
	return &file_biz_services_peer_mux_local_peer_proto_enumTypes[2]
}

func (x PeerSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeerSource.Descriptor instead.
func (PeerSource) EnumDescriptor() ([]byte, []int) {
	return file_biz_services_peer_mux_local_peer_proto_rawDescGZIP(), []int{2}
}

type IPInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientIp      []byte                 `protobuf:"bytes,1,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	ReportIp      []byte                 `protobuf:"bytes,2,opt,name=report_ip,json=reportIp,proto3" json:"report_ip,omitempty"`
	ReportV4      []byte                 `protobuf:"bytes,3,opt,name=report_v4,json=reportV4,proto3" json:"report_v4,omitempty"`
	ReportV6      []byte                 `protobuf:"bytes,4,opt,name=report_v6,json=reportV6,proto3" json:"report_v6,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPInfo) Reset() {
	*x = IPInfo{}
	mi := &file_biz_services_peer_mux_local_peer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPInfo) ProtoMessage() {}

func (x *IPInfo) ProtoReflect() protoreflect.Message {
	mi := &file_biz_services_peer_mux_local_peer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPInfo.ProtoReflect.Descriptor instead.
func (*IPInfo) Descriptor() ([]byte, []int) {
	return file_biz_services_peer_mux_local_peer_proto_rawDescGZIP(), []int{0}
}

func (x *IPInfo) GetClientIp() []byte {
	if x != nil {
		return x.ClientIp
	}
	return nil
}

func (x *IPInfo) GetReportIp() []byte {
	if x != nil {
		return x.ReportIp
	}
	return nil
}

func (x *IPInfo) GetReportV4() []byte {
	if x != nil {
		return x.ReportV4
	}
	return nil
}

func (x *IPInfo) GetReportV6() []byte {
	if x != nil {
		return x.ReportV6
	}
	return nil
}

type OfferDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Sdp           string                 `protobuf:"bytes,2,opt,name=sdp,proto3" json:"sdp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfferDetail) Reset() {
	*x = OfferDetail{}
	mi := &file_biz_services_peer_mux_local_peer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfferDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferDetail) ProtoMessage() {}

func (x *OfferDetail) ProtoReflect() protoreflect.Message {
	mi := &file_biz_services_peer_mux_local_peer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferDetail.ProtoReflect.Descriptor instead.
func (*OfferDetail) Descriptor() ([]byte, []int) {
	return file_biz_services_peer_mux_local_peer_proto_rawDescGZIP(), []int{1}
}

func (x *OfferDetail) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OfferDetail) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

type Offer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OfferId       string                 `protobuf:"bytes,1,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	Offer         *OfferDetail           `protobuf:"bytes,2,opt,name=offer,proto3" json:"offer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Offer) Reset() {
	*x = Offer{}
	mi := &file_biz_services_peer_mux_local_peer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Offer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Offer) ProtoMessage() {}

func (x *Offer) ProtoReflect() protoreflect.Message {
	mi := &file_biz_services_peer_mux_local_peer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Offer.ProtoReflect.Descriptor instead.
func (*Offer) Descriptor() ([]byte, []int) {
	return file_biz_services_peer_mux_local_peer_proto_rawDescGZIP(), []int{2}
}

func (x *Offer) GetOfferId() string {
	if x != nil {
		return x.OfferId
	}
	return ""
}

func (x *Offer) GetOffer() *OfferDetail {
	if x != nil {
		return x.Offer
	}
	return nil
}

type PeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InfoHash      []byte                 `protobuf:"bytes,1,opt,name=info_hash,json=infoHash,proto3" json:"info_hash,omitempty"`
	Ip            *IPInfo                `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Left          uint64                 `protobuf:"varint,4,opt,name=left,proto3" json:"left,omitempty"`
	Downloaded    uint64                 `protobuf:"varint,5,opt,name=downloaded,proto3" json:"downloaded,omitempty"`
	Uploaded      uint64                 `protobuf:"varint,6,opt,name=uploaded,proto3" json:"uploaded,omitempty"`
	LastSeen      int64                  `protobuf:"varint,7,opt,name=lastSeen,proto3" json:"lastSeen,omitempty"`
	UserAgent     string                 `protobuf:"bytes,8,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	PeerId        []byte                 `protobuf:"bytes,9,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Event         PeerEvent              `protobuf:"varint,10,opt,name=event,proto3,enum=PeerEvent" json:"event,omitempty"`
	Type          PeerType               `protobuf:"varint,11,opt,name=type,proto3,enum=PeerType" json:"type,omitempty"`
	Offers        []*Offer               `protobuf:"bytes,12,rep,name=offers,proto3" json:"offers,omitempty"`
	Source        PeerSource             `protobuf:"varint,13,opt,name=source,proto3,enum=PeerSource" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_biz_services_peer_mux_local_peer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_biz_services_peer_mux_local_peer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_biz_services_peer_mux_local_peer_proto_rawDescGZIP(), []int{3}
}

func (x *PeerInfo) GetInfoHash() []byte {
	if x != nil {
		return x.InfoHash
	}
	return nil
}

func (x *PeerInfo) GetIp() *IPInfo {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *PeerInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *PeerInfo) GetLeft() uint64 {
	if x != nil {
		return x.Left
	}
	return 0
}

func (x *PeerInfo) GetDownloaded() uint64 {
	if x != nil {
		return x.Downloaded
	}
	return 0
}

func (x *PeerInfo) GetUploaded() uint64 {
	if x != nil {
		return x.Uploaded
	}
	return 0
}

func (x *PeerInfo) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *PeerInfo) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *PeerInfo) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

func (x *PeerInfo) GetEvent() PeerEvent {
	if x != nil {
		return x.Event
	}
	return PeerEvent_Unknown
}

func (x *PeerInfo) GetType() PeerType {
	if x != nil {
		return x.Type
	}
	return PeerType_Bittorrent
}

func (x *PeerInfo) GetOffers() []*Offer {
	if x != nil {
		return x.Offers
	}
	return nil
}

func (x *PeerInfo) GetSource() PeerSource {
	if x != nil {
		return x.Source
	}
	return PeerSource_HTTP
}

var File_biz_services_peer_mux_local_peer_proto protoreflect.FileDescriptor

var file_biz_services_peer_mux_local_peer_proto_rawDesc = []byte{
	0x0a, 0x26, 0x62, 0x69, 0x7a, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x70,
	0x65, 0x65, 0x72, 0x2f, 0x6d, 0x75, 0x78, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x2f, 0x70, 0x65,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7c, 0x0a, 0x06, 0x49, 0x50, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x70, 0x12,
	0x1b, 0x0a, 0x09, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x08, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x49, 0x70, 0x12, 0x1b, 0x0a, 0x09,
	0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x76, 0x34, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x08, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x56, 0x34, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x5f, 0x76, 0x36, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x72, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x56, 0x36, 0x22, 0x33, 0x0a, 0x0b, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x64, 0x70,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x64, 0x70, 0x22, 0x46, 0x0a, 0x05, 0x4f,
	0x66, 0x66, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x22, 0x0a, 0x05, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x05, 0x6f, 0x66,
	0x66, 0x65, 0x72, 0x22, 0xfe, 0x02, 0x0a, 0x08, 0x50, 0x65, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x08, 0x69, 0x6e, 0x66, 0x6f, 0x48, 0x61, 0x73, 0x68, 0x12, 0x17, 0x0a,
	0x02, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x49, 0x50, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x65,
	0x66, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x12, 0x1e,
	0x0a, 0x0a, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0a, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x08, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61,
	0x73, 0x74, 0x53, 0x65, 0x65, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6c, 0x61,
	0x73, 0x74, 0x53, 0x65, 0x65, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20,
	0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e,
	0x50, 0x65, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x1d, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09,
	0x2e, 0x50, 0x65, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x1e, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x73, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x06, 0x2e, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x73, 0x12,
	0x23, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0b, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x06, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x2a, 0x41, 0x0a, 0x09, 0x50, 0x65, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0b,
	0x0a, 0x07, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x53,
	0x74, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x65, 0x64, 0x10, 0x03, 0x2a, 0x2a, 0x0a, 0x08, 0x50, 0x65, 0x65, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x42, 0x69, 0x74, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x57, 0x65, 0x62, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x10, 0x01, 0x2a, 0x27, 0x0a, 0x0a, 0x50, 0x65, 0x65, 0x72, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x54, 0x54, 0x50, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x55,
	0x44, 0x50, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x57, 0x53, 0x10, 0x02, 0x42, 0x1d, 0x5a, 0x1b,
	0x62, 0x69, 0x7a, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x70, 0x65, 0x65,
	0x72, 0x2f, 0x6d, 0x75, 0x78, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_biz_services_peer_mux_local_peer_proto_rawDescOnce sync.Once
	file_biz_services_peer_mux_local_peer_proto_rawDescData = file_biz_services_peer_mux_local_peer_proto_rawDesc
)

func file_biz_services_peer_mux_local_peer_proto_rawDescGZIP() []byte {
	file_biz_services_peer_mux_local_peer_proto_rawDescOnce.Do(func() {
		file_biz_services_peer_mux_local_peer_proto_rawDescData = protoimpl.X.CompressGZIP(file_biz_services_peer_mux_local_peer_proto_rawDescData)
	})
	return file_biz_services_peer_mux_local_peer_proto_rawDescData
}

var file_biz_services_peer_mux_local_peer_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_biz_services_peer_mux_local_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_biz_services_peer_mux_local_peer_proto_goTypes = []any{
	(PeerEvent)(0),      // 0: PeerEvent
	(PeerType)(0),       // 1: PeerType
	(PeerSource)(0),     // 2: PeerSource
	(*IPInfo)(nil),      // 3: IPInfo
	(*OfferDetail)(nil), // 4: OfferDetail
	(*Offer)(nil),       // 5: Offer
	(*PeerInfo)(nil),    // 6: PeerInfo
}
var file_biz_services_peer_mux_local_peer_proto_depIdxs = []int32{
	4, // 0: Offer.offer:type_name -> OfferDetail
	3, // 1: PeerInfo.ip:type_name -> IPInfo
	0, // 2: PeerInfo.event:type_name -> PeerEvent
	1, // 3: PeerInfo.type:type_name -> PeerType
	5, // 4: PeerInfo.offers:type_name -> Offer
	2, // 5: PeerInfo.source:type_name -> PeerSource
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_biz_services_peer_mux_local_peer_proto_init() }
func file_biz_services_peer_mux_local_peer_proto_init() {
	if File_biz_services_peer_mux_local_peer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_biz_services_peer_mux_local_peer_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_biz_services_peer_mux_local_peer_proto_goTypes,
		DependencyIndexes: file_biz_services_peer_mux_local_peer_proto_depIdxs,
		EnumInfos:         file_biz_services_peer_mux_local_peer_proto_enumTypes,
		MessageInfos:      file_biz_services_peer_mux_local_peer_proto_msgTypes,
	}.Build()
	File_biz_services_peer_mux_local_peer_proto = out.File
	file_biz_services_peer_mux_local_peer_proto_rawDesc = nil
	file_biz_services_peer_mux_local_peer_proto_goTypes = nil
	file_biz_services_peer_mux_local_peer_proto_depIdxs = nil
}
