// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.29.0
// source: biz/services/peer/mux_local/peer.proto

package mux_local

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PeerEvent int32

const (
	PeerEvent_Unknown   PeerEvent = 0
	PeerEvent_Started   PeerEvent = 1
	PeerEvent_Stopped   PeerEvent = 2
	PeerEvent_Completed PeerEvent = 3
)

// Enum value maps for PeerEvent.
var (
	PeerEvent_name = map[int32]string{
		0: "Unknown",
		1: "Started",
		2: "Stopped",
		3: "Completed",
	}
	PeerEvent_value = map[string]int32{
		"Unknown":   0,
		"Started":   1,
		"Stopped":   2,
		"Completed": 3,
	}
)

func (x PeerEvent) Enum() *PeerEvent {
	p := new(PeerEvent)
	*p = x
	return p
}

func (x PeerEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeerEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_biz_services_peer_mux_local_peer_proto_enumTypes[0].Descriptor()
}

func (PeerEvent) Type() protoreflect.EnumType {
	return &file_biz_services_peer_mux_local_peer_proto_enumTypes[0]
}

func (x PeerEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeerEvent.Descriptor instead.
func (PeerEvent) EnumDescriptor() ([]byte, []int) {
	return file_biz_services_peer_mux_local_peer_proto_rawDescGZIP(), []int{0}
}

type IPInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientIp  []byte `protobuf:"bytes,1,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	ReportIp  []byte `protobuf:"bytes,2,opt,name=report_ip,json=reportIp,proto3" json:"report_ip,omitempty"`
	ReportV4  []byte `protobuf:"bytes,3,opt,name=report_v4,json=reportV4,proto3" json:"report_v4,omitempty"`
	Report_V6 []byte `protobuf:"bytes,4,opt,name=report_V6,json=reportV6,proto3" json:"report_V6,omitempty"`
}

func (x *IPInfo) Reset() {
	*x = IPInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biz_services_peer_mux_local_peer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IPInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPInfo) ProtoMessage() {}

func (x *IPInfo) ProtoReflect() protoreflect.Message {
	mi := &file_biz_services_peer_mux_local_peer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPInfo.ProtoReflect.Descriptor instead.
func (*IPInfo) Descriptor() ([]byte, []int) {
	return file_biz_services_peer_mux_local_peer_proto_rawDescGZIP(), []int{0}
}

func (x *IPInfo) GetClientIp() []byte {
	if x != nil {
		return x.ClientIp
	}
	return nil
}

func (x *IPInfo) GetReportIp() []byte {
	if x != nil {
		return x.ReportIp
	}
	return nil
}

func (x *IPInfo) GetReportV4() []byte {
	if x != nil {
		return x.ReportV4
	}
	return nil
}

func (x *IPInfo) GetReport_V6() []byte {
	if x != nil {
		return x.Report_V6
	}
	return nil
}

type PeerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InfoHash   []byte    `protobuf:"bytes,1,opt,name=info_hash,json=infoHash,proto3" json:"info_hash,omitempty"`
	Ip         *IPInfo   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port       int32     `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Left       uint64    `protobuf:"varint,4,opt,name=left,proto3" json:"left,omitempty"`
	Downloaded uint64    `protobuf:"varint,5,opt,name=downloaded,proto3" json:"downloaded,omitempty"`
	Uploaded   uint64    `protobuf:"varint,6,opt,name=uploaded,proto3" json:"uploaded,omitempty"`
	LastSeen   int64     `protobuf:"varint,7,opt,name=lastSeen,proto3" json:"lastSeen,omitempty"`
	UserAgent  string    `protobuf:"bytes,8,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	PeerId     []byte    `protobuf:"bytes,9,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Event      PeerEvent `protobuf:"varint,10,opt,name=event,proto3,enum=PeerEvent" json:"event,omitempty"`
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biz_services_peer_mux_local_peer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_biz_services_peer_mux_local_peer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_biz_services_peer_mux_local_peer_proto_rawDescGZIP(), []int{1}
}

func (x *PeerInfo) GetInfoHash() []byte {
	if x != nil {
		return x.InfoHash
	}
	return nil
}

func (x *PeerInfo) GetIp() *IPInfo {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *PeerInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *PeerInfo) GetLeft() uint64 {
	if x != nil {
		return x.Left
	}
	return 0
}

func (x *PeerInfo) GetDownloaded() uint64 {
	if x != nil {
		return x.Downloaded
	}
	return 0
}

func (x *PeerInfo) GetUploaded() uint64 {
	if x != nil {
		return x.Uploaded
	}
	return 0
}

func (x *PeerInfo) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *PeerInfo) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *PeerInfo) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

func (x *PeerInfo) GetEvent() PeerEvent {
	if x != nil {
		return x.Event
	}
	return PeerEvent_Unknown
}

var File_biz_services_peer_mux_local_peer_proto protoreflect.FileDescriptor

var file_biz_services_peer_mux_local_peer_proto_rawDesc = []byte{
	0x0a, 0x26, 0x62, 0x69, 0x7a, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x70,
	0x65, 0x65, 0x72, 0x2f, 0x6d, 0x75, 0x78, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x2f, 0x70, 0x65,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7c, 0x0a, 0x06, 0x49, 0x50, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x70, 0x12,
	0x1b, 0x0a, 0x09, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x08, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x49, 0x70, 0x12, 0x1b, 0x0a, 0x09,
	0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x76, 0x34, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x08, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x56, 0x34, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x5f, 0x56, 0x36, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x72, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x56, 0x36, 0x22, 0x9a, 0x02, 0x0a, 0x08, 0x50, 0x65, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x68, 0x61, 0x73, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x69, 0x6e, 0x66, 0x6f, 0x48, 0x61, 0x73, 0x68,
	0x12, 0x17, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x49,
	0x50, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6c, 0x65, 0x66, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x6c, 0x65, 0x66,
	0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x65,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x08, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x6c, 0x61, 0x73, 0x74, 0x53, 0x65, 0x65, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x6c, 0x61, 0x73, 0x74, 0x53, 0x65, 0x65, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75,
	0x73, 0x65, 0x72, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x65, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x65, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x20, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0a, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x2a, 0x41, 0x0a, 0x09, 0x50, 0x65, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0b, 0x0a,
	0x07, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x74,
	0x6f, 0x70, 0x70, 0x65, 0x64, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x65, 0x64, 0x10, 0x03, 0x42, 0x1d, 0x5a, 0x1b, 0x62, 0x69, 0x7a, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x70, 0x65, 0x65, 0x72, 0x2f, 0x6d, 0x75, 0x78, 0x5f,
	0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_biz_services_peer_mux_local_peer_proto_rawDescOnce sync.Once
	file_biz_services_peer_mux_local_peer_proto_rawDescData = file_biz_services_peer_mux_local_peer_proto_rawDesc
)

func file_biz_services_peer_mux_local_peer_proto_rawDescGZIP() []byte {
	file_biz_services_peer_mux_local_peer_proto_rawDescOnce.Do(func() {
		file_biz_services_peer_mux_local_peer_proto_rawDescData = protoimpl.X.CompressGZIP(file_biz_services_peer_mux_local_peer_proto_rawDescData)
	})
	return file_biz_services_peer_mux_local_peer_proto_rawDescData
}

var file_biz_services_peer_mux_local_peer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_biz_services_peer_mux_local_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_biz_services_peer_mux_local_peer_proto_goTypes = []interface{}{
	(PeerEvent)(0),   // 0: PeerEvent
	(*IPInfo)(nil),   // 1: IPInfo
	(*PeerInfo)(nil), // 2: PeerInfo
}
var file_biz_services_peer_mux_local_peer_proto_depIdxs = []int32{
	1, // 0: PeerInfo.ip:type_name -> IPInfo
	0, // 1: PeerInfo.event:type_name -> PeerEvent
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_biz_services_peer_mux_local_peer_proto_init() }
func file_biz_services_peer_mux_local_peer_proto_init() {
	if File_biz_services_peer_mux_local_peer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_biz_services_peer_mux_local_peer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IPInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biz_services_peer_mux_local_peer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PeerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_biz_services_peer_mux_local_peer_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_biz_services_peer_mux_local_peer_proto_goTypes,
		DependencyIndexes: file_biz_services_peer_mux_local_peer_proto_depIdxs,
		EnumInfos:         file_biz_services_peer_mux_local_peer_proto_enumTypes,
		MessageInfos:      file_biz_services_peer_mux_local_peer_proto_msgTypes,
	}.Build()
	File_biz_services_peer_mux_local_peer_proto = out.File
	file_biz_services_peer_mux_local_peer_proto_rawDesc = nil
	file_biz_services_peer_mux_local_peer_proto_goTypes = nil
	file_biz_services_peer_mux_local_peer_proto_depIdxs = nil
}
