= Configuration

The configuration file is in YAML format, you can find the example configuration in the `conf/prod.yaml` file.

[cols="<,<,<"]
|===
|Name |Description |Default 

|ttl |The time of a peer announce next time. |3600s 
|intervalTask |The interval of the task to clean the expired peers. |600s 
|*mode* |trunker provides 3 running mode: memory, db and rpc|*required*,`memory`
|memory/database |Depends on your mode, this can be 2 different struct. | 
|useUnixSocket |Use Unix Socket instead tcp |false 
|hostPorts |The host and port of the server, For unix socket mode, this is the file name of the sock file. |`127.0.0.1:8888`
|useAnnounceIP |Allow peer to announce its IP in the query string. |true 
|enableEventProducer |Send peer event to the mq. Caution: This will produce tons of message. |false
|enableMetrics|Enable prometheus metrics|false
|metricsHostPorts|The host and port of the metrics server|`127.0.0.1:9091`
|udpServer| The config of the UDP server| false
|trackerId|A string that the client should send back on its next announcements. If absent and a previous announce sent a tracker id, do not discard the old value; keep using it.|`default`
|===

== Memory

=== What is memory mode?

Memory mode means that the tracker will store all the data in memory, which will cost more memory but have a better performance. Memory mode only save the data to the disk by interval or when the tracker is shutting down, and load the data from the disk when the tracker is launching (optional).

=== Config

If your mode is `memory`, you can use the following configuration.

[cols="<,<,<"]
|===
|Name |Description |Default 

|enablePersist |Save the peers to the disk and load them while launching. |true
|maxPeersPerTorrent |The max number of peers per torrent. |100 
|shard |The number of shards. More shards will improve response time, by cost more memory. |16
|enableWS|Enable Websocket tracker for WebTorrents|false
|===

== Database

=== What is database mode?

In database mode, tracker will save all the data in the db, which is convenience for external analysis and backup. The performance is depended on the database, so please confirm your database is powerful enough. Currently only `MySQL` is supported and https://myrocks.io/[rocksdb] is recommended.

=== Config

If your mode is `database`, following configuration are *required*.

[cols="<,<,<"]
|===
|Name |Description |Default 

|database |The database name. |*required*, no default 
|host |The database host. |*required*, no default 
|port |The database port. |*required*, no default 
|user |The database user. |*required*, no default 
|pass |The database password. |*required*, no default 
|===

== RPC Mode
=== What is RPC mode?
In certain situations, due to the presence of bots like MarkScan, you might want to hide your Tracker server behind a secure ExitNode. For HTTP requests, such protection can be achieved through methods like reverse proxy. However, for UDP Trackers, forwarding can affect UDP communication. Therefore, trunker provides an RPC mode. By setting up two trunker instances on different devices, with one running as an RPC server and the other configured in RPC Mode, all requests sent to the client will be forwarded to the server via RPC, effectively hiding the real server.
[source]
----
                                                                              |
                                                                              |
                                                                              |
                                                                              | HTTP Announce
                                                                              |
                                                                              |
                                                                              |
                                                                              |
                                                                              |
                                                              +---------------v-----------------+
                                                              |                                 |
                                                              |              CDN                |
                                                              |                                 |
                                                              +---------------+-----------------+
                 |                                                            |
                 |                                                            |
                 | UDP Announce                                               |
                 |                                                            |
                 |                                                            |
                 |                                                            |
                 |                                            +---------------v----------------+
+----------------v--------------+                             |                                |
|                               |                             |                                |
|                               |          RPC Call           |                                |
|    Trunker on the exit-node   +---------------------------->|     The Real Tunker Server     |
|                               |                             |                                |
|                               |                             |                                |
+-------------------------------+                             +--------------------------------+
----
If your mode is `rpc`, following configuration are *required*.
[cols="<,<,<"]
|===
|Name |Description |Default

|enableServer|Enable the rpc server of not|`false`
|hostPort|The host and port of the rpc server listening|**required** if server is enabled
|remoteServer|The remote server address|**required** for rpc mode
|===

== UDP Server
Trunker provide a UDP implement of the Bittorrent tracker server, aka. https://www.bittorrent.org/beps/bep_0015.html[BEP-0015]

[cols="<,<,<"]
|===
|Name |Description |Default

|enable |Whether enable the UDP server|false
|hostPorts |The host and port of the UDP server. For listening both IPv4 and IPv6 address, please use `:6881` |`127.0.0.1:6881`
|===

CAUTION: UDP server can't be protected with CDN, you should protect it by yourself.



== JSON Config

JSON config is also supported with env `TRUNKER_CONFIG`, this will be useful for docker.

== Other Config
=== Cache
Trunker support to use redis as cache, which is useful for scrape.
The redis config is in the `cache` field.
[cols="<,<,<"]
|===
|Name |Description |Default

|enable |Enable redis cache|false
|host |Host of redis |
|port |Port of redis |
|===

=== Rocketmq
Trunker can send the peer event to the rocketmq, which is useful for the analysis.
The rocketmq config is in the `rocketmq` field.
[cols="<,<,<"]
|===
|Name |Description |Default
|topic| The topic of the rocketmq|*required*, no default
|endpoint| The endpoint of the rocketmq|*required*, no default